name: HelloMinecraft
main: me.smickles.HelloMinecraft.HelloMinecraft
version: 0.0.0.2
author: smickles

commands:
     hello:
          escription: This command requests a greeting.
          usage: /<command>